name: queuetrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Icons & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2

  # Firebase & Supabase
  firebase_core: ^4.1.0
  supabase_flutter: ^2.12.0

  # Utilities
  intl: ^0.20.2
  fluttertoast: ^9.0.0
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  url_launcher: ^6.3.2

  # PDF & Printing
  pdf: ^3.11.3
  printing: ^5.14.2

  # Notifications
  onesignal_flutter: ^5.3.4

  # Maps & Location
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0

  # Charts
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Icon Generators (Keep these here)
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

# ----------------------------------------
# 1. CONFIGURATION FOR APP ICON
# ----------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

# ----------------------------------------
# 2. CONFIGURATION FOR SPLASH SCREEN
# ----------------------------------------
flutter_native_splash:
  color: "#0D47A1" # Deep Blue Background
  image: "assets/app_icon.png"
  android_12:
    image: "assets/app_icon.png"
    color: "#0D47A1"

# ----------------------------------------
# FLUTTER ASSETS
# ----------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/